### ISSUE TITLE
navメニューgui作成

### ISSUE THREAD

**Issue by tomatoaiu** [jphacks/SD_1704#36]
layout.htmlを編集しようと思うよ

**Comment by tomatoaiu** [comment]
dopdownが反応しない！

**Comment by tomatoaiu** [comment]
login logoutが右側によらない

**Comment by tomatoaiu** [comment]
右側によならい問題解決

**Comment by tomatoaiu** [comment]
https://github.com/jphacks/SD_1704/pull/39

**Comment by tomatoaiu** [comment]
shoutページでheaderが表示されない

**Comment by s2mr** [comment]
追加Issue
- navバーの選択した項目に応じて太文字、下線を引く
- 各ページのnavバーの下にマージンを設ける
